version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      - 'POSTGRES_DB=ripe_ncc'
      - 'POSTGRES_USER=demouser'
      - 'POSTGRES_PASSWORD=demopassword'
    ports:
      - '5432:5432'

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ripe_ncc
      SPRING_DATASOURCE_USERNAME: demouser
      SPRING_DATASOURCE_PASSWORD: demopassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend